docs/Development-Setup.md, vcpkg-packages.bat
Added assimp as it was missing and a required dependency
=> chore: Added missing vcpkg packages

DustRiders/DustRiders/Camera.cpp, DustRiders/DustRiders/DustRiders.vcxproj, DustRiders/DustRiders/DustRiders.vcxproj.filters, DustRiders/DustRiders/Overlay.cpp, DustRiders/DustRiders/PhysicsSystem.cpp, DustRiders/DustRiders/PhysicsSystem.h, DustRiders/DustRiders/RenderingSystem.cpp, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/Vehicle.h, DustRiders/DustRiders/VertexBuffer.cpp, DustRiders/DustRiders/Window.h, DustRiders/DustRiders/basic.frag, DustRiders/DustRiders/basic.vert, DustRiders/DustRiders/main.cpp, DustRiders/DustRiders/snippetvehicle2common/SnippetVehicleHelpers.cpp, DustRiders/DustRiders/snippetvehicle2directdrive/SnippetVehicleDirectDrive.cpp, DustRiders/DustRiders/snippetvehicle2directdrive/SnippetVehicleRender.cpp
- Car rendered in window
- Fixes quaternion issue
- Added two AI cars
=> feat: Car Physics

DustRiders/DustRiders/Camera.cpp, DustRiders/DustRiders/Camera.h, DustRiders/DustRiders/main.cpp
- emoved redundant functionality from Camera class
=> simplify camera class

DustRiders/DustRiders/Entity.h, DustRiders/DustRiders/RenderingSystem.cpp, DustRiders/DustRiders/main.cpp
=> Add Model Scalling

DustRiders/DustRiders/Overlay.cpp, DustRiders/DustRiders/Overlay.h, DustRiders/DustRiders/main.cpp
- Game can be won or lost by being 50units ahead/behind the other cars (currently hardcoded to one car)
=> feat: Game win logic

DustRiders/DustRiders/InputHandler.cpp, DustRiders/DustRiders/InputHandler.h, DustRiders/DustRiders/Overlay.cpp, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/Vehicle.h, DustRiders/DustRiders/main.cpp, README.md
- Controller now uses triggers for acceleration and brakes instead of joysticks
- Right trigger is throttle, left trigger is brake, left button uses "reverse" instead of "forward"
- 'A' simulates a weapon firing
- Need to create a check for whether the button is has just started being pressed or not to prevent repeated readings of the same signal.
=> Controller Remapped for Better Use

DustRiders/DustRiders/Camera.cpp, DustRiders/DustRiders/Camera.h, DustRiders/DustRiders/RenderingSystem.cpp, DustRiders/DustRiders/RenderingSystem.h, DustRiders/DustRiders/Window.cpp, DustRiders/DustRiders/Window.h, DustRiders/DustRiders/main.cpp
- top-down camera
- full screen support
=> Yas Camera Updates

DustRiders/DustRiders/DustRiders.vcxproj, DustRiders/DustRiders/DustRiders.vcxproj.filters, DustRiders/DustRiders/InputHandler.cpp, DustRiders/DustRiders/InputHandler.h, DustRiders/DustRiders/Window.h, DustRiders/DustRiders/main.cpp, README.md
- Added keyboard inputs for controlling the car
- Keyboard inputs are used when no controller is available
- Controller inputs are used when a controller is available
- ESC key should close the window when using both keyboard or controller inputs (there are some interrupt issues to clear up but it works the majority of the time)
- Added documentation for each form of input the README
=> Added Keyboard Inputs

DustRiders/DustRiders/InputHandler.h, DustRiders/DustRiders/StateHandler.cpp, DustRiders/DustRiders/StateHandler.h, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/Vehicle.h, DustRiders/DustRiders/WindowCallbacks.h, DustRiders/DustRiders/main.cpp, docs/Game-Controls.md
- Added hot reload for vehicle parameters *.json files (UP on controller, 'R' on keyboard)
- Added game reset for game state, vehicle position, and vehicle velocity (Y on controller, 'Backspace' on keyboard)
=> Hot Reload and Reset

DustRiders/DustRiders/AIVehicle.cpp, DustRiders/DustRiders/AIVehicle.h, DustRiders/DustRiders/DustRiders.vcxproj, DustRiders/DustRiders/DustRiders.vcxproj.filters, DustRiders/DustRiders/Entity.h, DustRiders/DustRiders/Ground.h, DustRiders/DustRiders/Obstacle.cpp, DustRiders/DustRiders/Obstacle.h, DustRiders/DustRiders/PhysicsEntity.h, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/Vehicle.h, DustRiders/DustRiders/main.cpp
- refactored Entity to not accept transform in constructor arguments
=> feat: Rocks now load into world and interact with cars

DustRiders/DustRiders/DustRiders.vcxproj, DustRiders/DustRiders/DustRiders.vcxproj.filters, DustRiders/DustRiders/debug.frag, DustRiders/DustRiders/debug.vert, DustRiders/DustRiders/main.cpp
- Doesn't car about missing emission/specular textures
- Ambient light is brighter so it's always visible
- Shadows still allow for dimension to be seen
=> feat: Added debug shader

DustRiders/DustRiders/InputHandler.cpp, DustRiders/DustRiders/InputHandler.h, DustRiders/DustRiders/Overlay.cpp, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/main.cpp
- Sound only emits once per press (of keyboard key or of controller)
- Sound emits every time ray gun is pressed
=> fix: Ray gun sound correctly emits

DustRiders/DustRiders/DustRiders.vcxproj.filters
=> chore: Organize file filters

DustRiders/DustRiders/AIPathHandler.cpp, DustRiders/DustRiders/ChunkHandler.cpp, DustRiders/DustRiders/ChunkHandler.h, DustRiders/DustRiders/DustRiders.vcxproj, DustRiders/DustRiders/DustRiders.vcxproj.filters, DustRiders/DustRiders/Ground.cpp, DustRiders/DustRiders/LogWriter.cpp, DustRiders/DustRiders/ModelProvider.cpp, DustRiders/DustRiders/ModelProvider.h, DustRiders/DustRiders/ObstacleHandler.cpp, DustRiders/DustRiders/ObstacleHandler.h, DustRiders/DustRiders/PhysicsProvider.h, DustRiders/DustRiders/PhysicsSystem.cpp, DustRiders/DustRiders/PhysicsSystem.h, DustRiders/DustRiders/Provider.h, DustRiders/DustRiders/ShaderProvider.cpp, DustRiders/DustRiders/ShaderProvider.h, DustRiders/DustRiders/main.cpp
- Added a ground chunk handler
- Moved many items in main to providers
=> feat: Chunk loading system and providers

DustRiders/DustRiders/ChunkHandler.cpp, DustRiders/DustRiders/ChunkHandler.h, DustRiders/DustRiders/ObstacleHandler.cpp, DustRiders/DustRiders/ObstacleHandler.h, DustRiders/DustRiders/main.cpp
- Obstacles are now loaded per chunk
- Obstacles are cleared on game reset
- ChunkHandler now managed obstacles instead of main
=> feat: Improved chunk and obstacle handling

DustRiders/DustRiders/AIVehicle.cpp, DustRiders/DustRiders/ChunkHandler.h, DustRiders/DustRiders/ConstantsHelper.h, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/Vehicle.h, DustRiders/DustRiders/assets/constants.json
- Vehicle max speed increases, when chunkCounter is incremented
=> feat: Vehicles speed up with each map chunk

DustRiders/DustRiders/AIVehicle.cpp, DustRiders/DustRiders/AIVehicle.h, DustRiders/DustRiders/ConstantsHelper.h, DustRiders/DustRiders/RayBeam.cpp, DustRiders/DustRiders/RayBeam.h, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/assets/constants.json, DustRiders/DustRiders/main.cpp
- When shooting is possible, there is a 50% chance AI will shoot
- AI will delay 0.7 seconds from a possible target to attempting to shoot
- AI will shoot at players and self
- Increased view time for raybeam
=> feat: AI now shoots at players and itself

DustRiders/DustRiders/RayBeam.cpp, DustRiders/DustRiders/RenderingSystem.cpp, DustRiders/DustRiders/RenderingSystem.h, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/Vehicle.h, DustRiders/DustRiders/car.frag, DustRiders/DustRiders/car.vert, DustRiders/DustRiders/main.cpp
- Cars show red colouring for 0.5s when successfully hit
=> feat: Cars visually show hit

DustRiders/DustRiders/AIVehicle.cpp, DustRiders/DustRiders/InputHandler.cpp, DustRiders/DustRiders/InputHandler.h, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/Vehicle.h, DustRiders/DustRiders/VehicleHandler.h, DustRiders/DustRiders/main.cpp
- Up to three controllers can be connected and control the cars
=> feat: Controller multiplayer

DustRiders/DustRiders/DustRiders.vcxproj, DustRiders/DustRiders/DustRiders.vcxproj.filters, DustRiders/DustRiders/RayBeam.h, DustRiders/DustRiders/ShaderProvider.cpp, DustRiders/DustRiders/ShaderProvider.h, DustRiders/DustRiders/Vehicle.cpp, DustRiders/DustRiders/Vehicle.h, DustRiders/DustRiders/VehicleHandler.h, DustRiders/DustRiders/assets/models/car-flames.mtl, DustRiders/DustRiders/flame.frag, DustRiders/DustRiders/flame.vert
- Flames now show when throttle is pushed
- Flames scale to provide a smooth growth when throttle is pushed
- Added a shader for use for emission-only textures like flames and raybeams
=> Flames on Throttle

.vscode/settings.json, DustRiders/DustRiders/DebugDefines.h, DustRiders/DustRiders/DustRiders.vcxproj, DustRiders/DustRiders/DustRiders.vcxproj.filters, DustRiders/DustRiders/GameHandler.cpp, DustRiders/DustRiders/Geometry.h, DustRiders/DustRiders/Mesh.h, DustRiders/DustRiders/Model.h, DustRiders/DustRiders/RenderingSystem.cpp, DustRiders/DustRiders/RenderingSystem.h, DustRiders/DustRiders/ShaderProvider.cpp, DustRiders/DustRiders/ShaderProvider.h, DustRiders/DustRiders/car.vert, DustRiders/DustRiders/depth.frag, DustRiders/DustRiders/depth.vert, DustRiders/DustRiders/map.frag, DustRiders/DustRiders/map.vert, DustRiders/DustRiders/shadow.frag, DustRiders/DustRiders/shadow.vert
- Shadows implemented
- Slight peter panning on landscape shadows, but it's workable
=> feat: Shadows

DustRiders/DustRiders/GameHandler.cpp, DustRiders/DustRiders/Overlay.cpp
=> feat: Display which player is which car
